# Generated by Django 4.2.2 on 2023-06-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proposta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=256)),
                ("cpf", models.CharField(max_length=16)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("aprovada", models.BooleanField(default=False)),
            ],
        ),
    ]
